#include "hal_usb.h"
#include <string.h>

#ifdef UNIT_TEST
    static bool mock_usb_connected = false;
    static uint8_t mock_tx_buffer[256];
    static uint16_t mock_tx_len = 0;
    static bool mock_init_fail = false;
#else
    /* Physical STM32 USBX linkage */
    #include "ux_api.h"
    #include "ux_device_class_cdc_acm.h"
    
    /* These handles would be defined in the USBX initialization code generated by CubeMX */
    extern UX_SLAVE_CLASS_CDC_ACM *cdc_acm_instance;
#endif

usb_status_t hal_usb_init(void) {
#ifdef UNIT_TEST
    if (mock_init_fail) return USB_ERR_INIT;
    mock_usb_connected = true;
    return USB_OK;
#else
    /* TODO: For John - Ensure mx_usbx_device_init() is called in app_azure_rtos.c.
     * This function should initialize the USB hardware and the USBX stack. */
    return USB_OK; 
#endif
}

usb_status_t hal_usb_transmit(const uint8_t *data, uint16_t len) {
#ifdef UNIT_TEST
    if (len > sizeof(mock_tx_buffer)) return USB_ERR_TX;
    memcpy(mock_tx_buffer, data, len);
    mock_tx_len = len;
    return USB_OK;
#else
    if (cdc_acm_instance == NULL) return USB_ERR_TX;
    
    ULONG actual_length;
    UINT status = _ux_device_class_cdc_acm_write(cdc_acm_instance, (UCHAR *)data, len, &actual_length);
    
    return (status == UX_SUCCESS) ? USB_OK : USB_ERR_TX;
#endif
}

usb_status_t hal_usb_receive(uint8_t *data, uint16_t *len) {
#ifdef UNIT_TEST
    /* Simple loopback mock logic could go here */
    *len = 0;
    return USB_OK;
#else
    if (cdc_acm_instance == NULL) return USB_ERR_RX;

    ULONG actual_length;
    UINT status = _ux_device_class_cdc_acm_read(cdc_acm_instance, (UCHAR *)data, *len, &actual_length);
    
    *len = (uint16_t)actual_length;
    return (status == UX_SUCCESS) ? USB_OK : USB_ERR_RX;
#endif
}

bool hal_usb_is_connected(void) {
#ifdef UNIT_TEST
    return mock_usb_connected;
#else
    /* Check if the CDC ACM instance is valid and the device is in the CONFIGURED state */
    return (cdc_acm_instance != NULL);
#endif
}

#ifdef UNIT_TEST
/* Test Interfaces */
void _hal_usb_mock_set_connected(bool connected) { mock_usb_connected = connected; }
void _hal_usb_mock_inject_init_fail(bool fail) { mock_init_fail = fail; }
uint16_t _hal_usb_mock_get_tx_data(uint8_t *buf) {
    memcpy(buf, mock_tx_buffer, mock_tx_len);
    return mock_tx_len;
}
#endif
